language: python
python:
  - 2.7
  - 3.3
  - 3.4
env:
  - TEST_RUNNER=pytest
install:
  - pip install coveralls
script: make ci
after_success:
  - coveralls
notifications:
  email:
    on_success: never
    on_failure: always
